# main tasks for role `nginx`
-
  name: 'add repository'
  sudo: yes
  yum:
    name: 'http://nginx.org/packages/centos/6/noarch/RPMS/nginx-release-centos-6-0.el6.ngx.noarch.rpm'
    state: present

-
  name: 'install'
  sudo: yes
  yum:
    name: nginx
    state: present

-
  name: 'clean conf.d'
  sudo: yes
  file:
    path: '{{ item }}'
    state: absent
  with_items:
    - '/etc/nginx/conf.d/default.conf'
    - '/etc/nginx/conf.d/example_ssl.conf'

-
  name: 'chown log dir'
  sudo: yes
  file:
    path: '/var/log/nginx'
    owner: 'nginx'
    group: 'nginx'
    recurse: yes
    state: directory

-
  name: 'enable service'
  sudo: yes
  service:
    name: nginx
    enabled: yes
  notify: 'nginx-restarted'

