# main tasks for role `mysql-client`
-
  name: 'add repository'
  sudo: yes
  yum:
    name: 'http://dev.mysql.com/get/mysql-community-release-el6-5.noarch.rpm'
    state: present

-
  name: 'install'
  sudo: yes
  yum:
    name: '{{ item }}'
    state: present
  with_items:
    - mysql
    - mysql-devel

-
  name: 'install python mysql driver'
  sudo: yes
  yum:
    name: MySQL-python
    state: present

-
  name: 'get path of mysqldump'
  sudo: no
  command: 'which mysqldump'
  register: result

-
  name: 'set path of mysqldump'
  sudo: no
  set_fact:
    mysql_dump: '{{ result.stdout }}'

