# main tasks for role `mysql-server`
-
  name: 'install'
  sudo: yes
  yum:
    name: mysql-server
    state: present

-
  name: 'config'
  sudo: yes
  ini_file:
    dest: '/etc/my.cnf'
    section: 'mysqld'
    option: '{{ item.key }}'
    value: '{{ item.value }}'
  with_dict: mysql_server_config

-
  name: 'enable service'
  sudo: yes
  service:
    name: mysqld
    enabled: yes
  notify: 'mysqld-restarted'

-
  meta: flush_handlers

